# nothing here
CONFIG_LOG=y

#Enabling ZCBOR (Zero-Copy Binary Object Representation)
CONFIG_ZCBOR=y

#FLASH 
CONFIG_FLASH=y
CONFIG_FLASH_MAP=y
CONFIG_IMG_MANAGER=y
CONFIG_STREAM_FLASH=y
#CONFIG_FLASH_PAGE_LAYOUT=y
#CONFIG_FLASH_HAS_DRIVER_ENABLED=y

# BLE related
CONFIG_BT=y
#CONFIG_BT_HCI=y
CONFIG_BT_PERIPHERAL=y
CONFIG_BT_DEVICE_NAME="RUTUJA's BLE-1"
CONFIG_BT_FILTER_ACCEPT_LIST=y
CONFIG_BT_SMP=y #Secure Manager Protocol
CONFIG_BT_FIXED_PASSKEY=y
CONFIG_BT_BONDING_REQUIRED=y
CONFIG_BT_DEVICE_APPEARANCE=832
#CONFIG_BT_DIS=y
CONFIG_SETTINGS=y
CONFIG_BT_SIGNING=y
CONFIG_BT_ATT_PREPARE_COUNT=1
CONFIG_BT_PRIVACY=y
CONFIG_BT_SETTINGS=y
CONFIG_FLASH_PAGE_LAYOUT=y

CONFIG_BT_L2CAP_TX_MTU=498
CONFIG_BT_BUF_ACL_TX_SIZE=251
CONFIG_BT_BUF_ACL_RX_SIZE=502
CONFIG_BT_CTLR_DATA_LENGTH_MAX=251
CONFIG_NVS=y
CONFIG_SETTINGS_NVS=y

#MCUMGR
CONFIG_MCUMGR=y
CONFIG_MCUMGR_GRP_IMG=y
CONFIG_MCUMGR_GRP_OS=y

# Enabling Bluetooth as a transport protocol for the MCUMGR
CONFIG_MCUMGR_TRANSPORT_BT=y

#Enabled Authentication (Secured DFU considered)
CONFIG_MCUMGR_TRANSPORT_BT_AUTHEN=y

#Allowed building and compiling of Bootloader and application, then they get merged into hex file
CONFIG_BOOTLOADER_MCUBOOT=y

# Enable the LBS service
CONFIG_DK_LIBRARY=y

#Increase the number of maximum paired devices
CONFIG_BT_MAX_PAIRED=1

# Increase stack size for the main thread and System Workqueue
#CONFIG_SYSTEM_WORKQUEUE_PRIORITY=-1
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=4096
CONFIG_MAIN_STACK_SIZE=4096
CONFIG_LOG_BUFFER_SIZE=4096

CONFIG_NCS_SAMPLE_MCUMGR_BT_OTA_DFU=y

#CONFIG_BT_DEBUG_HCI_DRIVER=y

